### ISSUE TITLE
怎么SocksTunnelServer根本没在运行中？

### ISSUE THREAD

**Issue by luckypoem** [xxxsen/SocksTunnel#1]
root@AR:~/sockstunnel/build# ./SocksTunnelServer setting.json
Setting file:setting.json
root@AR:~/sockstunnel/build# ps aux|grep SocksTunnelServer
root     18489  0.0  0.1   4660   988 pts/2    S+   02:54   0:00 grep SocksTunnelServer
root@AR:~/sockstunnel/build#

谢谢你

**Comment by xxxsen** [comment]
@luckypoem 方便贴下setting.json的配置(记得隐藏服务端ip)吗？。。谢谢。。

**Comment by xxxsen** [comment]
@luckypoem 额。。那个setting.json 要把路径带上   ./SocksTunnelServer ./setting.json

**Comment by xxxsen** [comment]
@luckypoem  抱歉, 搞错了, 后面加了多进程后对配置文件需要使用绝对路径, 或者直接不加参数, 使用当前路径下的setting.json  (./SocksTunnelServer ./setting.json  ./SocksTunnelServer setting.json 都是错的)

**Comment by xxxsen** [comment]
@luckypoem 能解决问题不? 麻烦给点反馈哈。。

**Comment by luckypoem** [comment]
hi.
都不行。
root@AR:~/sockstunnel/build# ls
CMakeCache.txt	cmake_install.cmake  setting.json      SocksTunnelLocal
CMakeFiles	Makefile	     setting.json.bak  SocksTunnelServer
root@AR:~/sockstunnel/build#  ./SocksTunnelServer ./setting.json
Setting file:./setting.json
root@AR:~/sockstunnel/build# ./SocksTunnelServer
Setting file:/root/sockstunnel/build/setting.json
root@AR:~/sockstunnel/build# ps aux|grep SocksTunnelServer
root     18948  0.0  0.1   4660  1000 pts/2    S+   03:33   0:00 grep SocksTunnelServer
root@AR:~/sockstunnel/build# ./SocksTunnelServer /root/sockstunnel/build/setting.json
Setting file:/root/sockstunnel/build/setting.json
root@AR:~/sockstunnel/build# ps aux|grep SocksTunnelServer
root     18955  0.0  0.1   4660  1000 pts/2    S+   03:34   0:00 grep SocksTunnelServer
root@AR:~/sockstunnel/build#

怎么解决？

**Comment by luckypoem** [comment]
root@AR:~/sockstunnel/build# cat setting.json
{
  "remote_server":"my_vps_ip",
  "remote_port":9001,
  "local_server":"127.0.0.1",
  "local_port":9000,
  "password":"ilovepeijian",
  "method":["chacha20"],
  "user":{
    "hellotest":"hellotest",
    "ohmyfuck":"ohyourfuck?"
  },
  "auth_timeout":30,
  "remote_proc_count":4
}
root@AR:~/sockstunnel/build#

setting.json正确吗？

**Comment by xxxsen** [comment]
@luckypoem 拿你的配置试了下, 需要加上日志配置, 不然启动不了= =。(尴尬), 日志的配置也可以参考那个readme.md
```
{
  "remote_server":"xxxxxxx",
  "remote_port":9001,
  "local_server":"0.0.0.0",
  "local_port":9000,
  "password":"ilovepeijian",
  "method":["chacha20"],
  "user":{
    "hellotest":"hellotest",
    "ohmyfuck":"ohyourfuck?"
  },
  "auth_timeout":30,
  "remote_proc_count":4,
  "log_setting":"you log setting file, 这里需要绝对路径"
}
```

**Comment by xxxsen** [comment]
@luckypoem 更新了个版本, 现在不配置日志也不会启动失败了。。

**Comment by luckypoem** [comment]
hi.

git pull后，还是不行。你自己测试过，能启动SocksTunnelServer吗？？
root@AR:~/sockstunnel# git pull
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0
展开对象中: 100% (5/5), 完成.
来自 https://github.com/xxxsen/sockstunnel
   fa7ef5b..7aa8ddc  master     -> origin/master
更新 fa7ef5b..7aa8ddc
Fast-forward
 src/CommonLib/Logger.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
root@AR:~/sockstunnel# cd build
root@AR:~/sockstunnel/build# ls
CMakeCache.txt	cmake_install.cmake  setting.json      SocksTunnelLocal
CMakeFiles	Makefile	     setting.json.bak  SocksTunnelServer
root@AR:~/sockstunnel/build# ./SocksTunnelServer
Setting file:/root/sockstunnel/build/setting.json
root@AR:~/sockstunnel/build# ls
CMakeCache.txt	cmake_install.cmake  setting.json      SocksTunnelLocal
CMakeFiles	Makefile	     setting.json.bak  SocksTunnelServer
root@AR:~/sockstunnel/build# nano setting.json 
root@AR:~/sockstunnel/build# ./SocksTunnelServer
Setting file:/root/sockstunnel/build/setting.json
root@AR:~/sockstunnel/build#
root@AR:~/sockstunnel/build# ./SocksTunnelServer /root/sockstunnel/build/setting.json
Setting file:/root/sockstunnel/build/setting.json
root@AR:~/sockstunnel/build#

**Comment by xxxsen** [comment]
@luckypoem 最新的版本, 用你的配置文件测试是可以启动的啊。。

**Comment by luckypoem** [comment]
能否贴出./SocksTunnelServer /root/sockstunnel/build/setting.json的运行结果，以及ps aux|grep SocksTunnelServer的运行结果吗

**Comment by xxxsen** [comment]
@luckypoem 
```
{
  "remote_server":"0.0.0.0",
  "remote_port":9001,
  "local_server":"0.0.0.0",
  "local_port":9000,
  "password":"ilovepeijian",
  "method":["chacha20"],
  "user":{
    "hellotest":"hellotest",
    "ohmyfuck":"ohyourfuck?"
  },
  "auth_timeout":30,
  "remote_proc_count":4
}
```

```
xxx@VM-13-132-ubuntu:~/server/SocksTunnel.git/trunk/build$ ./SocksTunnelServer 
Setting file:/home/xxx/server/SocksTunnel.git/trunk/build/setting.json
xxx@VM-13-132-ubuntu:~/server/SocksTunnel.git/trunk/build$ !ps
ps aux|grep SocksTunnelServer
xxx      11741  0.0  0.0  30436   636 ?        S    17:07   0:00 ./SocksTunnelServer
xxx      11742  0.0  0.0  30436   636 ?        S    17:07   0:00 ./SocksTunnelServer
xxx      11743  0.0  0.0  30436   636 ?        S    17:07   0:00 ./SocksTunnelServer
xxx      11744  0.0  0.0  30436   636 ?        S    17:07   0:00 ./SocksTunnelServer
xxx      11746  0.0  0.0  10460   948 pts/6    S+   17:07   0:00 grep --color=auto SocksTunnelServer
```
```
tcp        0      0 0.0.0.0:9001            0.0.0.0:*               LISTEN      11741/SocksTunnelSe
```

**Comment by xxxsen** [comment]
@luckypoem 把你的remote_server这项改成0.0.0.0试下？

**Comment by luckypoem** [comment]
还是不行。怪事，难道跟我的vps是openvz vps有关？

root@AR:~/sockstunnel/build# ./SocksTunnelServer ~/sockstunnel/build/setting.json
Setting file:/root/sockstunnel/build/setting.json
root@AR:~/sockstunnel/build# ps aux|grep SocksTunnelServer
root     19603  0.0  0.1   4660   996 pts/3    S+   05:26   0:00 grep SocksTunnelServer
root@AR:~/sockstunnel/build# ls
CMakeCache.txt	cmake_install.cmake  setting.json      SocksTunnelLocal
CMakeFiles	Makefile	     setting.json.bak  SocksTunnelServer
root@AR:~/sockstunnel/build# cat setting.json 
{
  "remote_server":"0.0.0.0",
  "remote_port":9001,
  "local_server":"0.0.0.0",
  "local_port":9000,
  "password":"ilovepeijian",
  "method":["chacha20"],
  "user":{
    "hellotest":"hellotest",
    "ohmyfuck":"ohyourfuck?"
  },
  "auth_timeout":30,
  "remote_proc_count":4
}
root@AR:~/sockstunnel/build#

**Comment by xxxsen** [comment]
@luckypoem 这个应该没多大关系, 我这边用的测试机是腾讯云, 你可以把你的邮箱发给我(naivesen#gmail.com), 我弄个账号你上去编译测试下, 看下会不会跟你那边一样。。

**Comment by luckypoem** [comment]
hi.

跑是可跑起来。
testuser@VM-13-132-ubuntu:~/SocksTunnel/build$ cp ../setting.json .
testuser@VM-13-132-ubuntu:~/SocksTunnel/build$ ls
CMakeCache.txt  cmake_install.cmake  setting.json      SocksTunnelServer
CMakeFiles      Makefile             SocksTunnelLocal
testuser@VM-13-132-ubuntu:~/SocksTunnel/build$ ./SocksTunnelServer
Setting file:/home/testuser/SocksTunnel/build/setting.json
testuser@VM-13-132-ubuntu:~/SocksTunnel/build$ ps aux|grep SocksTunnelServer
testuser 13680  0.0  0.0  30436   640 ?        S    17:58   0:00 ./SocksTunnelServer
testuser 13681  0.0  0.0  30436   640 ?        S    17:58   0:00 ./SocksTunnelServer
testuser 13682  0.0  0.0  30436   640 ?        S    17:58   0:00 ./SocksTunnelServer
testuser 13683  0.0  0.0  30436   640 ?        S    17:58   0:00 ./SocksTunnelServer
testuser 13687  0.0  0.0  10460   944 pts/7    S+   17:58   0:00 grep --color=auto SocksTunnelServer
testuser@VM-13-132-ubuntu:~/SocksTunnel/build$

不过你的系统是ubuntu14.04,我的是debian 8,难道跟os有关？

**Comment by xxxsen** [comment]
@luckypoem 没在debian上跑过, ubuntu14.04, 15.04都没问题。。我弄个虚拟机试下debian。。。。

**Comment by luckypoem** [comment]
hi.
这次搞定。我干脆删了之前clone的SocksTunnel，重新clone一次。再搞一遍就ok了。
root@AR:~/SocksTunnel/build# ls
CMakeCache.txt	cmake_install.cmake  SocksTunnelLocal
CMakeFiles	Makefile	     SocksTunnelServer
root@AR:~/SocksTunnel/build# ./SocksTunnelServer
Setting file:/root/SocksTunnel/build/setting.json
root@AR:~/SocksTunnel/build# cp ../setting.json .
root@AR:~/SocksTunnel/build# ls
CMakeCache.txt	cmake_install.cmake  setting.json      SocksTunnelServer
CMakeFiles	Makefile	     SocksTunnelLocal
root@AR:~/SocksTunnel/build# ./SocksTunnelServer
Setting file:/root/SocksTunnel/build/setting.json
root@AR:~/SocksTunnel/build# ps aux|grep SocksTunnelServer
root     20162  0.0  0.0   6840   612 ?        S    06:11   0:00 ./SocksTunnelServer
root     20163  0.0  0.0   6840   612 ?        S    06:11   0:00 ./SocksTunnelServer
root     20164  0.0  0.0   6840   612 ?        S    06:11   0:00 ./SocksTunnelServer
root     20165  0.0  0.0   6840   600 ?        S    06:11   0:00 ./SocksTunnelServer
root     20167  0.0  0.1   4660   996 pts/3    S+   06:11   0:00 grep SocksTunnelServer
root@AR:~/SocksTunnel/build#

**Comment by xxxsen** [comment]
@luckypoem 好吧, 再试下有没其他问题, 没问题, 我这边把issue关了。。

**Comment by luckypoem** [comment]
不过在mac上，make失败。如何解决？
yudeMacBook-Air:~ brite$ git clone https://github.com/xxxsen/SocksTunnel sockstunnel-cmake-version
Cloning into 'sockstunnel-cmake-version'...
remote: Counting objects: 189, done.
remote: Compressing objects: 100% (96/96), done.
remote: Total 189 (delta 92), reused 186 (delta 89), pack-reused 0
Receiving objects: 100% (189/189), 66.06 KiB | 84.00 KiB/s, done.
Resolving deltas: 100% (92/92), done.
Checking connectivity... done.
yudeMacBook-Air:~ brite$ cd sockstunnel-cmake-version
yudeMacBook-Air:sockstunnel-cmake-version brite$ ls
CMakeLists.txt		log_template.conf	src
README.md		setting.json		test
yudeMacBook-Air:sockstunnel-cmake-version brite$ mkdir build
yudeMacBook-Air:sockstunnel-cmake-version brite$ cd build
yudeMacBook-Air:build brite$ cmake ..
-- The C compiler identification is AppleClang 7.3.0.7030031
-- The CXX compiler identification is AppleClang 7.3.0.7030031
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/brite/sockstunnel-cmake-version/build
yudeMacBook-Air:build brite$ ls
CMakeCache.txt		Makefile
CMakeFiles		cmake_install.cmake
yudeMacBook-Air:build brite$ make
Scanning dependencies of target SocksTunnelLocal
[  2%] Building CXX object CMakeFiles/SocksTunnelLocal.dir/src/CommonLib/Json.cpp.o
In file included from /Users/brite/sockstunnel-cmake-version/src/CommonLib/Json.cpp:1:
In file included from /Users/brite/sockstunnel-cmake-version/src/CommonLib/Json.h:15:
In file included from /Users/brite/sockstunnel-cmake-version/src/CommonLib/Reader.h:5:
In file included from /Users/brite/sockstunnel-cmake-version/src/CommonLib/SharedPtr.h:22:
/Users/brite/sockstunnel-cmake-version/src/CommonLib/Mutex.h:102:21: error: 
      unknown type name 'pthread_barrier_t'
            typedef pthread_barrier_t BarrierID;
                    ^
1 error generated.
make[2]: *** [CMakeFiles/SocksTunnelLocal.dir/src/CommonLib/Json.cpp.o] Error 1
make[1]: *** [CMakeFiles/SocksTunnelLocal.dir/all] Error 2
make: *** [all] Error 2
yudeMacBook-Air:build brite$

**Comment by xxxsen** [comment]
@luckypoem 这边没mac。。。这个相关的可以看下。 http://stackoverflow.com/questions/9042780/how-to-tell-netbeans-information-on-pthread-barrier-t

这里应该是编译的时候定义_POSIX_BARRIERS这个宏为一个正数才能使用pthread_barrier_t。。
定义宏的话, 在CMakeLists.txt里面
在这行
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
```
加上-D_POSIX_BARRIERS
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -D_POSIX_BARRIERS")
```
没法测试, 不知道对不对。。

**Comment by luckypoem** [comment]
还是不行。谢谢你。看来，只能在linux桌面系统，用你这个程序翻墙了。

**Comment by luckypoem** [comment]
hi.
可否在https://github.com/xxxsen/SocksTunnel/releases/中提供windows下的客户端程序下载呢？

**Comment by xxxsen** [comment]
@luckypoem windows可执行文件已更新, mac的, 我这边再弄个虚拟机试下。。

**Comment by xxxsen** [comment]
@luckypoem 已经添加mac编译支持了。。

**Comment by luckypoem** [comment]
hi.

我重新克隆，进行make还是失败。

yudeMacBook-Air:build brite$ ls
CMakeCache.txt		Makefile
CMakeFiles		cmake_install.cmake
yudeMacBook-Air:build brite$ make
[  2%] Building CXX object CMakeFiles/SocksTunnelLocal.dir/src/CommonLib/Logger.cpp.o
[  4%] Building CXX object CMakeFiles/SocksTunnelLocal.dir/src/CommonLib/Mutex.cpp.o
In file included from /Users/yuming/sockstunnel-cmake-version/src/CommonLib/Mutex.cpp:1:
In file included from /Users/yuming/sockstunnel-cmake-version/src/CommonLib/Mutex.h:8:
/Users/yuming/sockstunnel-cmake-version/src/CommonLib/Barrier/pthread_barrier.h:49:9: warning: 
      empty struct has size 0 in C, size 1 in C++ [-Wextern-c-compat]
typedef struct {
        ^
1 warning generated.
[  7%] Building CXX object CMakeFiles/SocksTunnelLocal.dir/src/CommonLib/StringUtils.cpp.o
[  9%] Building CXX object CMakeFiles/SocksTunnelLocal.dir/src/CommonLib/Timestamp.cpp.o
[ 11%] Building CXX object CMakeFiles/SocksTunnelLocal.dir/src/SocksTunnelLocal.cpp.o
In file included from /Users/yuming/sockstunnel-cmake-version/src/SocksTunnelLocal.cpp:5:
In file included from /Users/yuming/sockstunnel-cmake-version/src/SocksTunnelLocal.h:21:
In file included from /Users/yuming/sockstunnel-cmake-version/src/Common/ServerCommon.h:19:
In file included from /Users/yuming/sockstunnel-cmake-version/src/Common/../Crypto/CryptoHelper.h:13:
In file included from /Users/yuming/sockstunnel-cmake-version/src/Common/../Crypto/../CommonLib/SharedPtr.h:22:
In file included from /Users/yuming/sockstunnel-cmake-version/src/CommonLib/Mutex.h:8:
/Users/yuming/sockstunnel-cmake-version/src/CommonLib/Barrier/pthread_barrier.h:49:9: warning: 
      empty struct has size 0 in C, size 1 in C++ [-Wextern-c-compat]
typedef struct {
        ^
In file included from /Users/yuming/sockstunnel-cmake-version/src/SocksTunnelLocal.cpp:5:
In file included from /Users/yuming/sockstunnel-cmake-version/src/SocksTunnelLocal.h:21:
In file included from /Users/yuming/sockstunnel-cmake-version/src/Common/ServerCommon.h:21:
/Users/yuming/sockstunnel-cmake-version/src/Common/../Crypto/Rc4.h:9:10: fatal error: 
      'openssl/rc4.h' file not found
#include <openssl/rc4.h>
         ^
1 warning and 1 error generated.
make[2]: *** [CMakeFiles/SocksTunnelLocal.dir/src/SocksTunnelLocal.cpp.o] Error 1
make[1]: *** [CMakeFiles/SocksTunnelLocal.dir/all] Error 2
make: *** [all] Error 2
yudeMacBook-Air:build brite$ brew install openssl
Warning: openssl-1.0.2d_1 already installed
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
yudeMacBook-Air:build brite$

例外，你也把mac版的可执行文件也上传到https://github.com/xxxsen/SocksTunnel/tree/master/release/吧。谢谢你

**Comment by xxxsen** [comment]
@luckypoem 额。。编译的时候找不到这个文件openssl/rc4.h..这个的话。。。把libcrypto装上就有了, Mac的可执行文件已经上传了。

**Comment by luckypoem** [comment]
hi.
怎么装libcrypto？

**Comment by xxxsen** [comment]
@luckypoem 我这边是直接编译libevent。。然后就可以编译了SocksTunnel了。。
安装可以看下
http://stackoverflow.com/questions/9874728/openssl-install-issue-to-mac

**Comment by luckypoem** [comment]
在mac上编译还是遇挫。暂时不管它。下载你的https://raw.githubusercontent.com/xxxsen/SocksTunnel/master/release/Mac/SocksTunnelLocal到我的mac后，运行之：
$ bash SocksTunnelLocal
SocksTunnelLocal: SocksTunnelLocal: cannot execute binary file

你这个SocksTunnelLocal是从linux vps上下载下来的吗？因为我从我的linux vps上下载SocksTunnelLocal到mac后，运行它，提示的也是SocksTunnelLocal: SocksTunnelLocal: cannot execute binary file。

你能贴出你在你的mac虚拟机上运行SocksTunnelLocal所输出的结果吗？

**Comment by xxxsen** [comment]
@luckypoem 这2个的确就是从mac上编译出来的= =。。。。
```
sendeMac:build sen$ ls
CMakeCache.txt		SocksTunnelLocal	setting.json
CMakeFiles		SocksTunnelServer
Makefile		cmake_install.cmake
sendeMac:build sen$ vim setting.json 
sendeMac:build sen$ ps -ef | grep Sock
  501   324   218   0 11:06下午 ttys000    0:00.00 grep Sock
sendeMac:build sen$ ./SocksTunnelServer 
Setting file:/Users/sen/SocksTunnel/build/setting.json
sendeMac:build sen$ ps -ef | grep Sock
  501   328     1   0 11:06下午 ??         0:00.00 ./SocksTunnelServer
  501   329     1   0 11:06下午 ??         0:00.00 ./SocksTunnelServer
  501   330     1   0 11:06下午 ??         0:00.00 ./SocksTunnelServer
  501   331     1   0 11:06下午 ??         0:00.00 ./SocksTunnelServer
  501   333   218   0 11:06下午 ttys000    0:00.00 grep Sock
sendeMac:build sen$ uname -a
Darwin sendeMac.local 13.0.0 Darwin Kernel Version 13.0.0: Thu Sep 19 22:22:27 PDT 2013; root:xnu-2422.1.72~6/RELEASE_X86_64 x86_64
sendeMac:build sen$ 
```

**Comment by luckypoem** [comment]
hi.

yudeMacBook-Air:~ brite$ uname -a
Darwin yudeMacBook-Air.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
yudeMacBook-Air:~ brite$ bash SocksTunnelLocal
SocksTunnelLocal: SocksTunnelLocal: cannot execute binary file
yudeMacBook-Air:~ brite$

我的mac的内核版本是15.5.0，你的是13.0.0，难道是内核版本不同造成你编译出来的SocksTunnelLocal在我的mac上用不了？

**Comment by luckypoem** [comment]
hi.
我直接编译libevent遇错误，可以说说你编译libevent的具体步骤吗

**Comment by luckypoem** [comment]
看到了
wget https://github.com/libevent/libevent/releases/download/release-2.0.22-stable/libevent-2.0.22-stable.tar.gz
tar -zxf libevent-2.0.22-stable.tar.gz
cd libevent-2.0.22-stable
./configure
make 
（这一步要加参数才行：
make CPPFLAGS="-I/usr/local/opt/openssl/include" LDFLAGS="-L/usr/local/opt/openssl/lib" 这样就可以make成功了。不会遇到'openssl/bio.h' not found的提示。参见https://jira.mongodb.org/browse/CDRIVER-941 )
make install

不过翻不了墙啊。我两边都运行了程序：
服务器上：
root@AR:~/sockstunnel-cmake-version/build# ps aux|grep SocksTunnelServer
root     18869  0.0  0.1   6840   940 ?        S    03:51   0:00 ./SocksTunnelServer
root     18870  0.0  0.1   6840   940 ?        S    03:51   0:00 ./SocksTunnelServer
root     18871  0.0  0.0   6840   612 ?        S    03:51   0:00 ./SocksTunnelServer
root     18872  0.0  0.0   6840   600 ?        S    03:51   0:00 ./SocksTunnelServer
root     18987  0.0  0.1   4660  1000 pts/1    S+   04:25   0:00 grep SocksTunnelServer
root@AR:~/sockstunnel-cmake-version/build# cat setting.json
{
  "remote_server":"0.0.0.0",
  "remote_port":9001,
  "local_server":"127.0.0.1",
  "local_port":9000,
  "password":"mypassword",
  "method":["chacha20"],
  "user":{
    "abc":"xyz",
    "ohmyfuck":"ohyourfuck?"
  },
  "auth_timeout":30,
  "remote_proc_count":4
}
root@AR:~/sockstunnel-cmake-version/build#

mac上：
yudeMacBook-Air:build brite$ ps aux|grep SocksTunnelLocal
yuming          98384   0.0  0.0  2452248    820 s000  S+    4:24下午   0:00.01 grep SocksTunnelLocal
yuming          98343   0.0  0.0  2463872    240   ??  S     4:21下午   0:00.00 ./SocksTunnelLocal
yuming          98342   0.0  0.0  2463872    236   ??  S     4:21下午   0:00.00 ./SocksTunnelLocal
yuming          98341   0.0  0.0  2463872    512   ??  S     4:21下午   0:00.00 ./SocksTunnelLocal
yuming          98340   0.0  0.0  2454656    236   ??  S     4:21下午   0:00.00 ./SocksTunnelLocal
yudeMacBook-Air:build brite$ cat setting.json
{
  "remote_server":"my_vps_ip",
  "remote_port":9001,
  "local_server":"127.0.0.1",
  "local_port":9000,
  "password":"mypassword",
  "method":["chacha20"],
  "current_user":"abc",
  "current_pwd":"xyz",
  "local_proc_count":4
}
yudeMacBook-Air:build brite$

怎么回事呢？

**Comment by xxxsen** [comment]
@luckypoem 你应该多看下我写的readme= =。。。用户名和密码的长度我是有限制的。。。。还有建议把日志打开, 这样能够第一时间看到出现的问题。。。

**Comment by xxxsen** [comment]
@luckypoem 编译出现问题, 是因为你的库的include目录还有lib目录不在搜索的路径里面。。

**Comment by xxxsen** [comment]
@luckypoem “ SocksTunnelLocal: cannot execute binary file”问题, 这个真心不清楚了, ，，

**Comment by luckypoem** [comment]
哦，用户名和密码的长度是有限制的。“ 程序中对用户名的长度限制是6-16个字符, 密码字段的长度则是6-32个字符”！终于搞定，可以翻墙了。

**Comment by luckypoem** [comment]
谢谢你

**Comment by xxxsen** [comment]
@luckypoem 没啥,, 试用下, 有问题可以继续反馈, 这边写了这个东西之后几乎都没人用, 嘿嘿, 你可以算是第一个正式的用户了, 运行都没问题了, 这个issue就关了哦。
